CREATE TABLE Personas (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    Nombres VARCHAR2(50) NOT NULL, 
    Apellidos VARCHAR2(50) NOT NULL, 
    NumeroIdentificacion VARCHAR2(20) NOT NULL UNIQUE, 
    TipoIdentificacion VARCHAR2(5) CHECK (TipoIdentificacion IN ('CC', 'TI', 'NIT', 'PAS')) NOT NULL, 
    Email VARCHAR2(100) NOT NULL UNIQUE, 
    Salario NUMBER(10,2) CHECK (Salario >= 0) NOT NULL, 
    Estado VARCHAR2(10) CHECK (Estado IN ('ACTIVO', 'INACTIVO')) NOT NULL,
	IdentificacionCompleta AS (TipoIdentificacion || NumeroIdentificacion) VIRTUAL,
	NombreCompleto AS (Nombres || ' ' || Apellidos) VIRTUAL
);


